## YAML Template.
name: CraftTableAutomation
main: de.guntram.bukkit.crafttableautomation.CraftTableAutomation
version: 0.2
commands:
    cta:
        description: Whatever.
        usage: /cta list
        permission: cta.commands
        permission-message: You may not use cta.
